"""Initial migration

Revision ID: c92e80db6d4c
Revises: 
Create Date: 2024-10-24 11:56:18.937153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c92e80db6d4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('umidade', sa.Float(), nullable=False),
    sa.Column('vibracao', sa.Float(), nullable=False),
    sa.Column('deslocamento_x', sa.Float(), nullable=False),
    sa.Column('deslocamento_y', sa.Float(), nullable=False),
    sa.Column('deslocamento_z', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('senha', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('sensores')
    # ### end Alembic commands ###
